// Persona definitions: each entry maps a HubCity persona to its asset folder.
// Image files become posts; video files become reels (Moments).

const ASSETS = '/Users/tj/Documents/Claude/Projects/HubCity MVP/Assets';

export const PERSONAS = [
  // ─── Compton — Ambassadors ─────────────────────────────────────────────
  {
    handle: 'compton-advocate',
    displayName: 'Compton Advocate',
    role: 'city_ambassador',
    citySlug: 'compton',
    folder: `${ASSETS}/Compton Accounts/Amassadors/Compton Advocate Post`,
    bio: 'Reporting from the Hub City. News, culture, community.',
    followerCount: 8400,
    isCreator: true,
  },
  {
    handle: 'compton-cowboys',
    displayName: 'Compton Cowboys',
    role: 'city_ambassador',
    citySlug: 'compton',
    folder: `${ASSETS}/Compton Accounts/Amassadors/Compton Cowboys Post`,
    bio: 'Riding for our community. Black cowboy & cowgirl culture, Compton-grown.',
    followerCount: 16800,
    isCreator: true,
    socialLinks: { instagram: '@comptoncowboys' },
  },
  {
    handle: 'compton-museum',
    displayName: 'Compton Art & History Museum',
    role: 'city_ambassador',
    citySlug: 'compton',
    folder: `${ASSETS}/Compton Accounts/Amassadors/Compton Museum Art`,
    bio: 'Boundless echoes — preserving Black art & history in the Hub City.',
    followerCount: 4200,
    isCreator: true,
    websiteUrl: 'https://comptonmuseum.org',
  },
  {
    handle: 'compton-isnt-dangerous',
    displayName: "Compton Isn't Dangerous",
    role: 'city_ambassador',
    citySlug: 'compton',
    folder: `${ASSETS}/Compton Accounts/Amassadors/Compton isn't dangerous post`,
    bio: 'Changing the narrative. Real Compton, real people.',
    followerCount: 9100,
    isCreator: true,
  },
  {
    handle: 'fene310',
    displayName: 'Fene 310',
    role: 'city_ambassador',
    citySlug: 'compton',
    folder: `${ASSETS}/Compton Accounts/Amassadors/post fene310`,
    bio: 'Compton creative. Music, fashion, the streets that raised us.',
    followerCount: 3800,
    isCreator: true,
  },

  // ─── Compton — Creators ─────────────────────────────────────────────
  {
    handle: 'adizthebam',
    displayName: 'Adiz The Bam',
    role: 'content_creator',
    citySlug: 'compton',
    folder: `${ASSETS}/Compton Accounts/Creator/adizthebam post`,
    bio: 'Compton-bred. Stories from the block.',
    followerCount: 2100,
    isCreator: true,
  },
  {
    handle: 'andre-spicer',
    displayName: 'Andre Spicer',
    role: 'content_creator',
    citySlug: 'compton',
    folder: `${ASSETS}/Compton Accounts/Creator/post videos Andre spicer`,
    bio: 'Compton journalist, on the ground in the Hub City.',
    followerCount: 5300,
    isCreator: true,
  },

  // ─── LA — Creators ─────────────────────────────────────────────
  {
    handle: 'espresso-events',
    displayName: 'Espresso Events',
    role: 'content_creator',
    citySlug: 'los-angeles',
    folder: `${ASSETS}/LA Accounts/Creator/espresso events post`,
    bio: 'Coffee, culture, community. Pop-ups across LA.',
    followerCount: 6700,
    isCreator: true,
  },
  {
    handle: 'scentofhustle',
    displayName: 'Scent of Hustle',
    role: 'content_creator',
    citySlug: 'los-angeles',
    folder: `${ASSETS}/LA Accounts/Creator/scent of hustle post`,
    bio: 'Fragrance with a story. LA-made.',
    followerCount: 4100,
    isCreator: true,
  },
  {
    handle: 'theblkscript',
    displayName: 'The BLK Script',
    role: 'content_creator',
    citySlug: 'los-angeles',
    folder: `${ASSETS}/LA Accounts/Creator/theblkscript post`,
    bio: 'Black film, Black writing, Black storytelling. LA.',
    followerCount: 7900,
    isCreator: true,
  },

  // ─── LA — Resource Account ─────────────────────────────────────────────
  {
    handle: 'source-la',
    displayName: 'Source LA',
    role: 'resource_provider',
    citySlug: 'los-angeles',
    folder: `${ASSETS}/LA Accounts/Resource Account/LA Source post resource account`,
    bio: 'Resources, programs, opportunities for Angelenos.',
    followerCount: 12500,
    isCreator: true,
    websiteUrl: 'https://sourcela.org',
  },

  // ─── IE — Creator ─────────────────────────────────────────────
  {
    handle: 'leftright',
    displayName: 'Left Right',
    role: 'content_creator',
    citySlug: 'riverside',
    folder: `${ASSETS}/IE Accounts/Creator/leftright post`,
    bio: 'Inland Empire raised. Music, motion, momentum.',
    followerCount: 3200,
    isCreator: true,
  },

  // ─── Big Accounts — National Creators (subscription-priced) ─────────────
  {
    handle: 'breakfast-club',
    displayName: 'The Breakfast Club',
    role: 'content_creator',
    citySlug: null, // national
    folder: `${ASSETS}/Big Accounts/Breakfast Club Post`,
    bio: 'The world\'s most dangerous morning show.',
    followerCount: 4_200_000,
    isCreator: true,
    subscriptionPriceCents: 999,
    contentScope: 'national',
  },
  {
    handle: 'earn-your-leisure',
    displayName: 'Earn Your Leisure',
    role: 'content_creator',
    citySlug: null,
    folder: `${ASSETS}/Big Accounts/earn your leisure group`,
    bio: 'Financial literacy, business, ownership. EYL Network.',
    followerCount: 2_100_000,
    isCreator: true,
    subscriptionPriceCents: 1499,
    contentScope: 'national',
  },
  {
    handle: 'kevonstage',
    displayName: 'Kevon Stage',
    role: 'content_creator',
    citySlug: null,
    folder: `${ASSETS}/Big Accounts/kevonstage post`,
    bio: 'Comedian. Storyteller. Father. Husband. Loud.',
    followerCount: 1_650_000,
    isCreator: true,
    subscriptionPriceCents: 499,
    contentScope: 'national',
  },
  {
    handle: 'lil-duval',
    displayName: 'Lil Duval',
    role: 'content_creator',
    citySlug: null,
    folder: `${ASSETS}/Big Accounts/lil duval post`,
    bio: 'Just keep livin & smile. ❤️',
    followerCount: 5_400_000,
    isCreator: true,
    subscriptionPriceCents: 999,
    contentScope: 'national',
  },
];

// Businesses: each has an owner (a profile). Some owners are persona handles
// above (when they're a content creator). Most need their own owner profile.
export const BUSINESSES = [
  {
    slug: 'fakesmiles',
    name: 'FakeSmiles',
    category: 'retail',
    folder: `${ASSETS}/Compton Accounts/Businesses/FakeSmiles Business`,
    citySlug: 'compton',
    description: 'Streetwear out of Compton. Smiles on every fit.',
    address: '1500 N Long Beach Blvd, Compton, CA 90221',
    ownerHandle: 'fakesmiles-owner',
    ownerName: 'FakeSmiles',
    ownerBio: 'Streetwear from the Hub City.',
  },
  {
    slug: 'glamorous-mane',
    name: 'Glamorous Mane',
    category: 'beauty',
    folder: `${ASSETS}/Compton Accounts/Businesses/Glamorous Mane business`,
    citySlug: 'compton',
    description: 'Hair, lashes, glow. Compton\'s glamour spot.',
    address: '811 S Long Beach Blvd, Compton, CA 90221',
    ownerHandle: 'glamorous-mane-owner',
    ownerName: 'Glamorous Mane',
    ownerBio: 'Beauty for the Hub City.',
  },
  {
    slug: 'pucker-up',
    name: 'Pucker Up',
    category: 'beauty',
    folder: `${ASSETS}/Compton Accounts/Businesses/Pucker Up Post`,
    citySlug: 'compton',
    description: 'Lip & beauty studio. Compton-grown.',
    address: '305 N Long Beach Blvd, Compton, CA 90221',
    ownerHandle: 'pucker-up-owner',
    ownerName: 'Pucker Up',
    ownerBio: 'Lips, lashes, love. Compton.',
  },
  {
    slug: 'bflyy-la',
    name: 'BFlyy LA',
    category: 'retail',
    folder: `${ASSETS}/LA Accounts/Businesses/bflyyla post`,
    citySlug: 'los-angeles',
    description: 'LA streetwear. Statement fits.',
    address: '700 S Hill St, Los Angeles, CA 90014',
    ownerHandle: 'bflyy-la-owner',
    ownerName: 'BFlyy LA',
    ownerBio: 'LA streetwear.',
  },
];

// Community groups: each has a creator (a city ambassador or city official
// since RLS requires those roles to insert).
export const GROUPS = [
  {
    slug: 'be-safe-stay-dangerous',
    name: 'Be Safe Stay Dangerous',
    category: 'other',
    citySlug: 'compton',
    folder: `${ASSETS}/Compton Accounts/Community/be safe stay dangerous group`,
    description: 'Compton mindset. Be safe out there. Stay dangerous in your craft.',
    creatorHandle: 'compton-advocate',
  },
  {
    slug: 'compton-runclub',
    name: 'Compton Run Club',
    category: 'sports',
    citySlug: 'compton',
    folder: `${ASSETS}/Compton Accounts/Community/compton runclub group`,
    description: 'Saturday mornings. Hub City miles. Everyone welcome.',
    creatorHandle: 'compton-advocate',
  },
  {
    slug: 'south-central-runclub',
    name: 'South Central Run Club',
    category: 'sports',
    citySlug: 'los-angeles',
    folder: `${ASSETS}/LA Accounts/Community/south central runclub group`,
    description: 'South Central pace. We move together.',
    creatorHandle: 'source-la',
    creatorRoleOverride: 'city_ambassador',
  },
  {
    slug: 'blk-film-space',
    name: 'BLK Film Space',
    category: 'other',
    citySlug: 'los-angeles',
    folder: `${ASSETS}/LA Accounts/Community/Blk film space`,
    description: 'Black filmmakers, writers, producers. LA collective.',
    creatorHandle: 'source-la',
    creatorRoleOverride: 'city_ambassador',
  },
  {
    slug: 'long-beach-runclub',
    name: 'Long Beach Run Club',
    category: 'sports',
    citySlug: 'long-beach',
    folder: `${ASSETS}/Long Beach Accounts/Community/long beach run club group`,
    description: 'LBC miles, every weekend. The pace is yours.',
    creatorHandle: 'long-beach-runclub-owner',
    createOwner: {
      displayName: 'Long Beach Run Club',
      bio: 'LBC running collective.',
      role: 'city_ambassador',
      citySlug: 'long-beach',
    },
  },
];
