-- ============================================================
-- Hub City App — Seed Schools Data
-- Move hardcoded school data from page.tsx into the database
-- ============================================================

-- Add metadata column for extra fields not in schema (schoolColors, etc.)
ALTER TABLE schools ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

-- ============================================================
-- HIGH SCHOOLS
-- ============================================================

INSERT INTO schools (name, slug, level, address, grades, phone, district, mascot, colors, enrollment, rating, tagline, established, highlights, programs, notable_alumni, image_url, website, is_published, metadata)
VALUES
(
  'Compton High School',
  'compton-high-school',
  'high_school',
  '601 S Acacia Ave, Compton, CA 90220',
  '9-12',
  '(310) 639-4321',
  NULL,
  'Tarbabes',
  '[{"hex": "#1E40AF", "name": "Blue"}, {"hex": "#60A5FA", "name": "White"}]'::jsonb,
  1650,
  4.2,
  'Where Champions Are Made',
  1896,
  ARRAY['CIF Football Champions', 'Award-Winning Band', 'STEM Magnet Program'],
  ARRAY['AP Courses', 'AVID', 'Athletics', 'Performing Arts', 'ROTC'],
  ARRAY['Kevin Costner', 'Venus Williams'],
  '/images/generated/compton-high.png',
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Blue & White", "schoolColors": ["#1E40AF", "#60A5FA"]}'::jsonb
),
(
  'Dominguez High School',
  'dominguez-high-school',
  'high_school',
  '15301 S San Jose Ave, Compton, CA 90221',
  '9-12',
  '(310) 631-7981',
  NULL,
  'Dons',
  '[{"hex": "#DC2626", "name": "Red"}, {"hex": "#FCA5A5", "name": "White"}]'::jsonb,
  1480,
  4.0,
  'Excellence Through Unity',
  1952,
  ARRAY['Track & Field Powerhouse', 'Visual Arts Program', 'College Prep Focus'],
  ARRAY['AP Courses', 'CTE Pathways', 'Athletics', 'Visual Arts', 'Robotics'],
  ARRAY['Willie McGinest', 'Antonio Gates'],
  '/images/generated/dominguez-high.png',
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Red & White", "schoolColors": ["#DC2626", "#FCA5A5"]}'::jsonb
),
(
  'Centennial High School',
  'centennial-high-school',
  'high_school',
  '2606 N Central Ave, Compton, CA 90222',
  '9-12',
  '(310) 604-4064',
  NULL,
  'Apaches',
  '[{"hex": "#15803D", "name": "Green"}, {"hex": "#86EFAC", "name": "Gold"}]'::jsonb,
  1320,
  4.1,
  'Building Tomorrow''s Leaders',
  1954,
  ARRAY['Health Sciences Academy', 'Strong Community Bonds', 'Rising Basketball Program'],
  ARRAY['Health Sciences', 'AP Courses', 'Athletics', 'Dance Team', 'Tutoring Center'],
  ARRAY[]::TEXT[],
  '/images/generated/centennial-high.png',
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Green & Gold", "schoolColors": ["#15803D", "#86EFAC"]}'::jsonb
),
(
  'Lynwood High School',
  'lynwood-high-school',
  'high_school',
  '4050 E Imperial Hwy, Lynwood, CA 90262',
  '9-12',
  '(310) 886-1600',
  NULL,
  'Knights',
  '[{"hex": "#1D4ED8", "name": "Blue"}, {"hex": "#FCD34D", "name": "Gold"}]'::jsonb,
  2100,
  3.9,
  'Knights Rise Together',
  1940,
  ARRAY['Award-Winning Marching Band', 'Large Campus', 'Diverse Programs'],
  ARRAY['AP Courses', 'Marching Band', 'Athletics', 'Engineering Pathway', 'Media Arts'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Lynwood Unified", "colors_text": "Blue & Gold", "schoolColors": ["#1D4ED8", "#FCD34D"]}'::jsonb
),

-- ============================================================
-- MIDDLE SCHOOLS
-- ============================================================

(
  'Walton Middle School',
  'walton-middle-school',
  'middle_school',
  '820 W Magnolia St, Compton, CA 90220',
  '6-8',
  '(310) 639-4306',
  NULL,
  'Warriors',
  '[{"hex": "#1E3A5F", "name": "Navy"}, {"hex": "#60A5FA", "name": "Gold"}]'::jsonb,
  720,
  3.8,
  'Preparing Warriors for the Future',
  1955,
  ARRAY['Strong Math Program', 'After-School Enrichment', 'Student Leadership'],
  ARRAY['STEM Enrichment', 'Music', 'Sports', 'Tutoring', 'Student Council'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Navy & Gold", "schoolColors": ["#1E3A5F", "#60A5FA"]}'::jsonb
),
(
  'Whaley Middle School',
  'whaley-middle-school',
  'middle_school',
  '15509 S Wadsworth Ave, Compton, CA 90221',
  '6-8',
  '(310) 898-6465',
  NULL,
  'Wildcats',
  '[{"hex": "#7C3AED", "name": "Purple"}, {"hex": "#C4B5FD", "name": "White"}]'::jsonb,
  650,
  3.7,
  'Wildcats Lead the Way',
  1962,
  ARRAY['Technology Lab', 'Art Program', 'Community Garden'],
  ARRAY['Computer Lab', 'Art', 'Music', 'Sports', 'Garden Club'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Purple & White", "schoolColors": ["#7C3AED", "#C4B5FD"]}'::jsonb
),
(
  'Davis Middle School',
  'davis-middle-school',
  'middle_school',
  '501 S Santa Fe Ave, Compton, CA 90221',
  '6-8',
  '(310) 639-4311',
  NULL,
  'Dragons',
  '[{"hex": "#059669", "name": "Green"}, {"hex": "#6EE7B7", "name": "White"}]'::jsonb,
  580,
  3.9,
  'Where Dragons Soar',
  1958,
  ARRAY['Reading Champions', 'Science Fair Winners', 'Mentorship Program'],
  ARRAY['Reading Lab', 'Science Club', 'Sports', 'Mentorship', 'Drama'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Green & White", "schoolColors": ["#059669", "#6EE7B7"]}'::jsonb
),
(
  'Roosevelt Middle School',
  'roosevelt-middle-school',
  'middle_school',
  '1200 E Compton Blvd, Compton, CA 90221',
  '6-8',
  '(310) 639-4316',
  NULL,
  'Rough Riders',
  '[{"hex": "#9F1239", "name": "Maroon"}, {"hex": "#FCA5A5", "name": "Gold"}]'::jsonb,
  690,
  3.8,
  'Riders of Excellence',
  1951,
  ARRAY['Music Program', 'Basketball Legacy', 'College Readiness Prep'],
  ARRAY['Band', 'Basketball', 'Academic Decathlon', 'Art', 'Coding Club'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Maroon & Gold", "schoolColors": ["#9F1239", "#FCA5A5"]}'::jsonb
),
(
  'Bunche Middle School',
  'bunche-middle-school',
  'middle_school',
  '12700 S Aranbe Ave, Compton, CA 90222',
  '6-8',
  NULL,
  NULL,
  'Bears',
  '[{"hex": "#78350F", "name": "Brown"}, {"hex": "#D97706", "name": "Gold"}]'::jsonb,
  540,
  3.6,
  'Bears Build Bright Futures',
  1965,
  ARRAY['Named for Nobel Peace Prize Winner', 'Community Focus', 'Enrichment Programs'],
  ARRAY['After-School Program', 'Music', 'Sports', 'Tutoring', 'Peer Mediation'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Brown & Gold", "schoolColors": ["#78350F", "#D97706"]}'::jsonb
),
(
  'Willowbrook Middle School',
  'willowbrook-middle-school',
  'middle_school',
  '1600 E 120th St, Compton, CA 90222',
  '6-8',
  NULL,
  NULL,
  'Wolves',
  '[{"hex": "#374151", "name": "Silver"}, {"hex": "#9CA3AF", "name": "Black"}]'::jsonb,
  610,
  3.7,
  'Wolves Run Together',
  1960,
  ARRAY['PBIS Award School', 'Tech Integration', 'Active PTA'],
  ARRAY['Technology', 'Sports', 'Art', 'Student Government', 'Yearbook'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Silver & Black", "schoolColors": ["#374151", "#9CA3AF"]}'::jsonb
),

-- ============================================================
-- ELEMENTARY SCHOOLS
-- ============================================================

(
  'Tibby Elementary',
  'tibby-elementary',
  'elementary',
  '621 N Burris Ave, Compton, CA 90221',
  'K-5',
  '(310) 639-4351',
  NULL,
  'Tigers',
  '[{"hex": "#EA580C", "name": "Orange"}, {"hex": "#FDBA74", "name": "Black"}]'::jsonb,
  420,
  4.0,
  'Little Tigers, Big Dreams',
  1948,
  ARRAY['Reading Excellence Award', 'Safe School Award', 'Parent Engagement Leader'],
  ARRAY['Reading Lab', 'After-School Care', 'Art', 'Music', 'Garden'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Orange & Black", "schoolColors": ["#EA580C", "#FDBA74"]}'::jsonb
),
(
  'Dickison Elementary',
  'dickison-elementary',
  'elementary',
  '1424 E Pine St, Compton, CA 90221',
  'K-5',
  '(310) 639-4356',
  NULL,
  'Dolphins',
  '[{"hex": "#0284C7", "name": "Blue"}, {"hex": "#67E8F9", "name": "Teal"}]'::jsonb,
  380,
  4.1,
  'Diving Into Learning',
  1952,
  ARRAY['STEM Focus', 'Dual Language Program', 'Active Community'],
  ARRAY['STEM', 'Dual Language', 'After-School', 'Music', 'Physical Ed'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Blue & Teal", "schoolColors": ["#0284C7", "#67E8F9"]}'::jsonb
),
(
  'Anderson Elementary',
  'anderson-elementary',
  'elementary',
  '515 W Alondra Blvd, Compton, CA 90220',
  'K-5',
  '(310) 639-4361',
  NULL,
  'Eagles',
  '[{"hex": "#DC2626", "name": "Red"}, {"hex": "#3B82F6", "name": "Blue"}]'::jsonb,
  410,
  3.9,
  'Eagles Soar High',
  1946,
  ARRAY['Character Counts Program', 'Science Garden', 'Family Nights'],
  ARRAY['Character Ed', 'Science Garden', 'Sports', 'Tutoring', 'PTA Events'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Red & Blue", "schoolColors": ["#DC2626", "#3B82F6"]}'::jsonb
),
(
  'Emerson Elementary',
  'emerson-elementary',
  'elementary',
  '421 N Bradfield Ave, Compton, CA 90221',
  'K-5',
  NULL,
  NULL,
  'Stars',
  '[{"hex": "#D97706", "name": "Gold"}, {"hex": "#1E3A5F", "name": "Navy"}]'::jsonb,
  350,
  3.8,
  'Every Child a Star',
  1955,
  ARRAY['Arts Integration', 'Small Class Sizes', 'Caring Staff'],
  ARRAY['Arts', 'Reading', 'Math Lab', 'Music', 'After-School'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Gold & Navy", "schoolColors": ["#D97706", "#1E3A5F"]}'::jsonb
),
(
  'Washington Elementary',
  'washington-elementary',
  'elementary',
  '1100 W Compton Blvd, Compton, CA 90220',
  'K-5',
  NULL,
  NULL,
  'Lions',
  '[{"hex": "#CA8A04", "name": "Gold"}, {"hex": "#16A34A", "name": "Green"}]'::jsonb,
  440,
  4.0,
  'Where Lions Learn to Lead',
  1941,
  ARRAY['Leadership Program', 'Bilingual Staff', 'Modern Library'],
  ARRAY['Leadership', 'Library Program', 'ESL', 'Music', 'Physical Ed'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Gold & Green", "schoolColors": ["#CA8A04", "#16A34A"]}'::jsonb
),
(
  'McKinley Elementary',
  'mckinley-elementary',
  'elementary',
  '2909 E Caldwell St, Compton, CA 90221',
  'K-5',
  NULL,
  NULL,
  'Mustangs',
  '[{"hex": "#B91C1C", "name": "Red"}, {"hex": "#374151", "name": "Black"}]'::jsonb,
  390,
  3.7,
  'Mustangs Gallop Toward Success',
  1950,
  ARRAY['Math Achievement Award', 'Anti-Bullying Champion', 'New Playground'],
  ARRAY['Math Enrichment', 'Anti-Bullying', 'Sports', 'Dance', 'Coding'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Red & Black", "schoolColors": ["#B91C1C", "#374151"]}'::jsonb
),
(
  'Bursch Elementary',
  'bursch-elementary',
  'elementary',
  '1711 S Burris Ave, Compton, CA 90221',
  'K-5',
  NULL,
  NULL,
  'Bobcats',
  '[{"hex": "#0D9488", "name": "Teal"}, {"hex": "#94A3B8", "name": "Silver"}]'::jsonb,
  360,
  3.8,
  'Bobcats Building Bright Futures',
  1957,
  ARRAY['Technology Integration', 'Wellness Program', 'Parent Workshops'],
  ARRAY['Tech Lab', 'Wellness', 'Reading', 'Art', 'After-School'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Teal & Silver", "schoolColors": ["#0D9488", "#94A3B8"]}'::jsonb
),
(
  'Mayo Elementary',
  'mayo-elementary',
  'elementary',
  '2600 W Caldwell St, Compton, CA 90220',
  'K-5',
  NULL,
  NULL,
  'Hawks',
  '[{"hex": "#15803D", "name": "Green"}, {"hex": "#EAB308", "name": "Gold"}]'::jsonb,
  370,
  3.9,
  'Hawks Take Flight',
  1949,
  ARRAY['Green School Initiative', 'Music Program', 'Community Events'],
  ARRAY['Environmental Ed', 'Music', 'Sports', 'Gardening', 'Tutoring'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Green & Gold", "schoolColors": ["#15803D", "#EAB308"]}'::jsonb
),
(
  'Kelly Elementary',
  'kelly-elementary',
  'elementary',
  '1428 N Paulsen Ave, Compton, CA 90222',
  'K-5',
  NULL,
  NULL,
  'Knights',
  '[{"hex": "#7C3AED", "name": "Purple"}, {"hex": "#CBD5E1", "name": "Silver"}]'::jsonb,
  340,
  3.8,
  'Little Knights, Big Hearts',
  1953,
  ARRAY['Character Education', 'Reading Champions', 'Talent Show'],
  ARRAY['Character Ed', 'Reading', 'Art', 'Music', 'Physical Ed'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Purple & Silver", "schoolColors": ["#7C3AED", "#CBD5E1"]}'::jsonb
),
(
  'Jefferson Elementary',
  'jefferson-elementary',
  'elementary',
  '1424 W 145th St, Compton, CA 90220',
  'K-5',
  NULL,
  NULL,
  'Jaguars',
  '[{"hex": "#1F2937", "name": "Black"}, {"hex": "#EAB308", "name": "Gold"}]'::jsonb,
  380,
  3.7,
  'Jaguars on the Prowl for Knowledge',
  1947,
  ARRAY['Literacy Focus', 'STEAM Fridays', 'Family Reading Night'],
  ARRAY['STEAM', 'Literacy', 'Sports', 'Drama', 'After-School'],
  ARRAY[]::TEXT[],
  NULL,
  NULL,
  true,
  '{"district_name": "Compton Unified", "colors_text": "Black & Gold", "schoolColors": ["#1F2937", "#EAB308"]}'::jsonb
),

-- ============================================================
-- COLLEGE
-- ============================================================

(
  'Compton College',
  'compton-college',
  'college',
  '1111 E Artesia Blvd, Compton, CA 90221',
  'Community College',
  '(310) 900-1600',
  NULL,
  'Tartars',
  '[{"hex": "#1D4ED8", "name": "Blue"}, {"hex": "#F2A900", "name": "Gold"}]'::jsonb,
  8500,
  4.3,
  'Your Future Starts Here',
  1927,
  ARRAY['Newly Accredited', 'Free Tuition (Compton Promise)', 'State-of-the-Art Facilities'],
  ARRAY['Transfer Programs', 'Nursing', 'Welding', 'Business', 'Child Development', 'Athletics'],
  ARRAY['Kendrick Lamar', 'Serena Williams'],
  '/images/generated/compton-college.png',
  'compton.edu',
  true,
  '{"district_name": null, "colors_text": "Blue & Gold", "schoolColors": ["#1D4ED8", "#F2A900"]}'::jsonb
)

ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  level = EXCLUDED.level,
  address = EXCLUDED.address,
  grades = EXCLUDED.grades,
  phone = EXCLUDED.phone,
  mascot = EXCLUDED.mascot,
  colors = EXCLUDED.colors,
  enrollment = EXCLUDED.enrollment,
  rating = EXCLUDED.rating,
  tagline = EXCLUDED.tagline,
  established = EXCLUDED.established,
  highlights = EXCLUDED.highlights,
  programs = EXCLUDED.programs,
  notable_alumni = EXCLUDED.notable_alumni,
  image_url = EXCLUDED.image_url,
  website = EXCLUDED.website,
  metadata = EXCLUDED.metadata,
  updated_at = now();
